### ISSUE TITLE
getMaxValue() misleading comments

### ISSUE THREAD

**Issue by claper87-zz** [mentzbb/SimpleMap1#1]
Hi!

I found the comments inside the  following method to be  misleading

```
public Integer getMaxValue(Map<String, Integer> inMap)
    {
        // change this method to return the key of the largest value stored
        // in the supplied 'inMap'

        return null;
    }
```

To me it says to return the **Key** of the map where the largest value is stored. So in the following map: a =>36, b=>15, c=>49. The resulting value should be "c" .

should the comment read:

>  change this method to return the largest value stored  in the supplied 'inMap'

instead? 

or should the method signature be:
`public String getMaxValue(Map<String, Integer> inMap)`
?

**Comment by keirbowden** [comment]
Great catch Clara - I can't actually remember which way around I wanted this to work! The tests are looking for the largest value from the map so I'll update the comment to reflect that.

**Comment by keirbowden** [comment]
This is now fixed - thanks for the report. I've invited you to join this org as a mentor so you can fix things yourself if you want to.
